language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4.1"
script:
  - istanbul cover ./node_modules/.bin/grunt --report lcovonly && istanbul report text && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf coverage
before_script:
  - npm install -g istanbul
  - npm install coveralls