language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_script:
  - yarn add --dev coveralls
