language: node_js
node_js:
- "8"
- "9"
- "10"
cache:
  yarn: true
  directories:
  - node_modules

stages:
- test
- name: deploy
  if: branch = master && type = push
jobs:
  include:
  - stage: test
    script:
    - yarn test
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    before_script:
    - yarn install --dev coveralls
  - stage: deploy
    install: true
    before_install:
    - 'curl -H "Cache-Control: no-cache" https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash'
    before_script:
    - cd src/ && fossa && cd ../
    script:
    - yarn build:doc
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      local-dir: docs
      on:
        branch: master



script:
  -
before_script:
  - yarn add --dev coveralls
